image: Ubuntu

build: off

stack: jdk 11

install:

build_script:
  - ./gradlew --console=plain jar

artifacts:
  - path: "build/libs/*.jar"

skip_tags: true

version: "{build}"

deploy:
  release: MultiplayerHC-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: h0k3EFcI2oVZp614pFswIB19uHRqFdBhQheAhnZjipoLyjInl8R8wXuUeWFTlOY6
  artifact: /build\/libs\/.*\.jar/
  draft: false
  prerelease: false
  on:
    branch: master
